spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxx:xxxxx/xxxxx?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: xxxxx
    password: xxxxx
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
  redis:
    host: xxxxx
    port: 6379
    password: xxxxx
    database: 0
    lettuce:
      pool:
        max-idle: 4
        max-active: 8
        max-wait: 1000
        min-idle: 2
    stream:
      group: group-order
      consumer: consumer-1
      name: ordermq
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
